version: '3.9'

services:
  mongodb:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres:

networks:
  backend:
    driver: bridge